export { borschtWithCabbageAndPotatoes } from './borschtWithCabbageAndPotatoes';
export { mainWhiteSauce } from './mainWhiteSauce';
export { buckwheatPorridgeCrumbly } from './buckwheatPorridgeCrumbly';
export { ricePorridgeCrumbly } from './ricePorridgeCrumbly';
export { viscousPorridgeWithPumpkin } from './viscousPorridgeWithPumpkin';
export { mainRedSauce } from './mainRedSauce';
export { coldBorscht } from './coldBorscht';
export { potatoSoupWithPasta } from './potatoSoupWithPasta';
export { vegetableStew } from './vegetableStew';